// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJ-3wBZRUUEwfCJiV1-nVdsp6PW79ds5U',
    appId: '1:161129343073:android:82effb7a7ada97d0e26220',
    messagingSenderId: '161129343073',
    projectId: 'food-dash-c07c0',
    storageBucket: 'food-dash-c07c0.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCofVW9YxggJbxr8rmgMwRY67G_0z-kQ7I',
    appId: '1:161129343073:web:0e23b8874aa3a8d9e26220',
    messagingSenderId: '161129343073',
    projectId: 'food-dash-c07c0',
    authDomain: 'food-dash-c07c0.firebaseapp.com',
    storageBucket: 'food-dash-c07c0.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsKAkHTC7It6V75uUFkN2G9MqzTwIZbuw',
    appId: '1:161129343073:ios:aaaada9e5d3e0cd5e26220',
    messagingSenderId: '161129343073',
    projectId: 'food-dash-c07c0',
    storageBucket: 'food-dash-c07c0.firebasestorage.app',
    iosBundleId: 'com.example.biteDash',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsKAkHTC7It6V75uUFkN2G9MqzTwIZbuw',
    appId: '1:161129343073:ios:aaaada9e5d3e0cd5e26220',
    messagingSenderId: '161129343073',
    projectId: 'food-dash-c07c0',
    storageBucket: 'food-dash-c07c0.firebasestorage.app',
    iosBundleId: 'com.example.biteDash',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCofVW9YxggJbxr8rmgMwRY67G_0z-kQ7I',
    appId: '1:161129343073:web:fce54158a1a1fb3fe26220',
    messagingSenderId: '161129343073',
    projectId: 'food-dash-c07c0',
    authDomain: 'food-dash-c07c0.firebaseapp.com',
    storageBucket: 'food-dash-c07c0.firebasestorage.app',
  );

}